source 'https://rubygems.org'


gem 'rails', '4.2.0'
gem 'rails-api'

gem 'devise_token_auth'

# gem 'spring', group: :development

gem 'rack-cors', require: 'rack/cors'

gem 'mysql2', '~> 0.3.18'

gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

group  :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers', github: 'thoughtbot/shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'faker'
end

# => for cron
gem 'whenever', require: false